# .bashrc
# User specific variables
export GOPATH=$HOME/Code/gocode
export EDITOR=vim

export PS1="${BLU}\u${WHI}@${PUR}\H ${GRE}\t ${PUR}\W${NUL} > "
export SHELL="/bin/bash"

# Attach to tmux if session exists or create a new session.
if [ -z $TMUX && -t 0 ]; then
	tmux attach
else
	tmux
fi

if [ -d $HOME/gocode ]; then
	mkdir $HOME/gocode
fi

alias vi="vim"

alias clip="xclip -selection c"
alias song="youtube-dl -x --audio-format \"wav\" --metadata-from-title \"%(artist)s - %(title)s\""
