# .bashrc
# User specific variables
export GOPATH=$HOME/Code/gocode
export EDITOR=vim

# Attach to tmux if session exists or create a new session.
if [ -z $TMUX ]; then
	tmux attach
else
	tmux
fi

if [ -d $HOME/gocode ]; then
	mkdir $HOME/gocode
fi


alias clip="xclip -selection c"
alias song="youtube-dl -x --audio-format \"wav\" --metadata-from-title \"%(artist)s - %(title)s\""
